### ISSUE TITLE
C-23-M-D-CV-CAL-0001_Civil Work Calculation

### ISSUE THREAD

**Issue by devanggacahyop** [ciriajasa/DED#100]
**Work Breakdown :** 

- [ ] Slope stability analysis
- [ ] Retaining Wall type & design structure calculation
- [ ] Earth Work Plan and Design Calculation

**Timeline :** April 7, 2023 - April 20, 2023

**Follow this Link to Open Document**
**Native :** 
**PDF :**
**Feedback :** 

**Note :**
Display/view from Microsoft Word will be different from the Display/view of Google Word. To edit native, please download the original file.
