### ISSUE TITLE
C-23-M-D-WT-CAL-0001_Water & Wastewater Treatment Plant Analysis

### ISSUE THREAD

**Issue by ciriajasa** [ciriajasa/DED#125]
**Work Breakdown :** 

- [ ] Rain harvesting process flow
- [ ] Rain harvesting flowrate & storage calculation
- [ ] Rain harvesting schematic diagram
- [ ] Wastewater treatment process flow
- [ ] Wastewater treatment plant schematic diagram

**Timeline :** April 3, 2023-April 14, 2023

**Follow this Link to Open Document**
**Native :** 
**PDF :**
**Feedback :** 

**Note :**
Display/view from Microsoft Word will be different from the Display/view of Google Word. To edit native, please download the original file.
