### ISSUE TITLE
C-23-M-D-ST-CAL-0001_Building Structural Calculation

### ISSUE THREAD

**Issue by ciriajasa** [ciriajasa/DED#126]
**Work Breakdown :** 

- [ ] Material & Standard
- [ ] Structural Design Method
- [ ] Load & Load Combinations
- [ ] Foundation type & design calculation
- [ ] Structural Model Analysis

**Timeline :** March 31, 2023 - May 18, 2023

**Follow this Link to Open Document**
**Native :** 
**PDF :**
**Feedback :** 

**Note :**
Display/view from Microsoft Word will be different from the Display/view of Google Word. To edit native, please download the original file.
