### ISSUE TITLE
C-23-M-D-HD-CAL-0002_Drainage system Calculation

### ISSUE THREAD

**Issue by ciriajasa** [ciriajasa/DED#127]
**Work Breakdown :** 
- [ ] drainage scheme calculation
- [ ] hydraulic calculation for drainage design
- [ ] springs water pond
- [ ] hydraulic calculation of main building drainage system

**Timeline :** April 14, 2023 - May 4, 2023

**Follow this Link to Open Document**
**Native :** 
**PDF :**
**Feedback :** 

**Note :**
Display/view from Microsoft Word will be different from the Display/view of Google Word. To edit native, please download the original file.
