### ISSUE TITLE
C-23-M-C-CV-CAL-0001_Civil Work Calculation

### ISSUE THREAD

**Issue by ciriajasa** [ciriajasa/DED#138]
**Work Breakdown :** 

- [ ] Slope stability analysis
- [ ] Retaining Wall type & design structure calculation
- [ ] Earth Work Plan and Design Calculation

**Timeline :** March 22, 2023 -  April 5, 2023

**Follow this Link to Open Document**
**Native :** 
**PDF :**
**Feedback :** 

**Note :**
Display/view from Microsoft Word will be different from the Display/view of Google Word. To edit native, please download the original file.
