### ISSUE TITLE
C-23-M-TS-ST-CAL-0001_Building Structural Calculation

### ISSUE THREAD

**Issue by ciriajasa** [ciriajasa/DED#42]
**Work Breakdown :** 

- [ ] Material & Standard
- [ ] Structural Design Method
- [ ] Load & Load Combinations
- [ ] Foundation type & design calculation
- [ ] Structural Model Analysis

**Timeline :** 

**Follow this Link to Open Document**
**Native :** 
**PDF :**
**Feedback :** 

**Note :**
Display/view from Microsoft Word will be different from the Display/view of Google Word. To edit native, please download the original file.
