### ISSUE TITLE
C-23-M-TS-AR-PLN-0001_Block Plan Analysis and General Assessment

### ISSUE THREAD

**Issue by ciriajasa** [ciriajasa/DED#45]
**Work Breakdown :** 

- [ ] Dimension analyses
- [ ] General Block Concept on topogaphy map
- [ ] Circulation Concept
- [ ] Vehicle Movement
- [ ] Waste Movement
- [ ] Emergency Movement
- [ ] Building Distances Concept
- [ ] Leveling and Grading Concept
- [ ] Security and Safety Concept

**Timeline :** April 13, 2023-April 19, 2023

**Follow this Link to Open Document**
**Native :** 
**PDF :**
**Feedback :** 

**Note :**
Display/view from Microsoft Word will be different from the Display/view of Google Word. To edit native, please download the original file.
